zeromq/jeromq

src/main/java/org/zeromq/ZAgent.java
src/main/java/org/zeromq/ZFrame.java
src/main/java/org/zeromq/ZLoop.java
src/main/java/org/zeromq/ZMQ.java
src/main/java/org/zeromq/ZPoller.java
src/main/java/org/zeromq/ZProxy.java
src/main/java/org/zeromq/ZStar.java
src/main/java/zmq/Clock.java
src/main/java/zmq/Ctx.java
src/main/java/zmq/DecoderBase.java
src/main/java/zmq/Dist.java
src/main/java/zmq/Encoder.java
src/main/java/zmq/Options.java
src/main/java/zmq/Pair.java
src/main/java/zmq/Pipe.java
src/main/java/zmq/Rep.java
src/main/java/zmq/Req.java
src/main/java/zmq/SessionBase.java
src/main/java/zmq/Signaler.java
src/main/java/zmq/SocketBase.java
src/main/java/zmq/StreamEngine.java
src/main/java/zmq/Sub.java
src/main/java/zmq/TcpConnecter.java
src/main/java/zmq/TcpListener.java
src/main/java/zmq/Utils.java
src/main/java/zmq/V1Encoder.java
src/main/java/zmq/YPipe.java

- documentation (javadoc links, ..)
- possible NPEs
- simplified some statements, removed unnecessary variables, ...

Fixed minor issues

---

src/main/java/org/zeromq/ZMQException.java

* Change to eventually support integration of jzmq-api into both JeroMQ and JZMQ via Maven profile

Added constructors to ZMQException

---

src/main/java/org/zeromq/ZAgent.java
src/main/java/org/zeromq/ZProxy.java
src/test/java/org/zeromq/TestZActor.java
src/test/java/org/zeromq/TestZMQ.java
src/test/java/org/zeromq/TestZProxy.java
src/test/java/org/zeromq/TestZThread.java
src/test/java/zmq/TestLastEndpoint.java
src/test/java/zmq/TestPairIpc.java

Better handling of Context termination and exit conditions in ZProxy.

Z improvements

---

src/main/java/zmq/Dist.java
src/main/java/zmq/FQ.java
src/main/java/zmq/LB.java
src/main/java/zmq/Mtrie.java
src/main/java/zmq/Pipe.java
src/main/java/zmq/SocketBase.java
src/main/java/zmq/Utils.java
src/main/java/zmq/XPub.java
src/main/java/zmq/ZMQ.java
src/test/java/zmq/TestUtils.java

Use a simple URI parser for ipv6 address

---

src/main/java/org/zeromq/ZMQ.java

https://github.com/zeromq/jeromq/issues/294

Rename setRouterHandlover() to setRouterHandover().

---

src/main/java/zmq/Command.java
src/main/java/zmq/Msg.java
src/main/java/zmq/PollerBase.java
src/main/java/zmq/Reaper.java
src/main/java/zmq/TcpConnecter.java
src/main/java/zmq/YPipe.java

This is a preparation to a bigger pull request, regarding some issues I encountered

Use of Atomic variables instead of volatile ones + final vars

---

src/main/java/org/zeromq/ZMsg.java

Do not proceeed next frame at send failure of previous frame

---

src/main/java/zmq/Decoder.java
src/main/java/zmq/Encoder.java
src/main/java/zmq/EncoderBase.java
src/main/java/zmq/V1Decoder.java
src/main/java/zmq/V1Encoder.java

Some performance improvements building on my previous commits (resolves #310).

Some performance improvements based on insights from #308.

---

README.md
pom.xml

Revert benjyz's contributed commits - Issue #327

Problem: benjyz no longer wants to be associated to JeroMQ

---

src/main/java/org/zeromq/ZLoop.java
src/main/java/org/zeromq/ZMQ.java
src/main/java/zmq/SocketBase.java
src/main/java/zmq/TcpAddress.java
src/main/java/zmq/TcpListener.java

Revert commits for #327

---

src/test/java/guide/rrclient.java

remove the comment. 
//  We never get here but clean up anyhow
indeed after the counter loop, code will get here

remove a c/p comment after counter loop

---

.travis.yml

Add JDK8 to travis test environments

---

src/main/java/org/zeromq/ZContext.java
src/main/java/zmq/SocketBase.java
src/test/java/guide/interrupt.java

Fixes https://github.com/zeromq/jeromq/issues/147.

Allow setLinger after a context is terminated

---

src/main/java/zmq/Pipe.java

Fix NullPointerException in zmq.Pipe

---

CONTRIBUTING.md
README.md
scripts/run-example

README adjustments; add CONTRIBUTING.md and run-example script

---

CHANGELOG.md

Preparing for 0.4.0 release ( #406 )

0.4.0 changelog

---

README.md
src/main/java/org/zeromq/ZProxy.java
src/main/java/zmq/Ctx.java
src/main/java/zmq/Msg.java
src/main/java/zmq/ZMQ.java
src/main/java/zmq/io/SessionBase.java
src/main/java/zmq/io/StreamEngine.java
src/main/java/zmq/io/mechanism/Mechanism.java
src/main/java/zmq/io/mechanism/NullMechanism.java
src/main/java/zmq/io/mechanism/curve/CurveClientMechanism.java
src/main/java/zmq/io/mechanism/curve/CurveServerMechanism.java
src/main/java/zmq/io/mechanism/plain/PlainClientMechanism.java
src/main/java/zmq/io/mechanism/plain/PlainServerMechanism.java
src/main/java/zmq/util/MultiMap.java
src/main/java/zmq/util/Wire.java
src/test/java/org/zeromq/TestZProxy.java
src/test/java/zmq/socket/stream/StreamTest.java

I discovered small things in latest PR when I wrote a new test for Stream socket.
Here is the result.
As a reminder, the custom encoder/decoder feature is not working anymore, I removed it from the README for the time being.

Small bug fixes

---

src/test/java/org/zeromq/DealerDealerTest.java
src/test/java/org/zeromq/PubSubTest.java
src/test/java/org/zeromq/ReqRepTest.java
src/test/java/org/zeromq/TestProxy.java
src/test/java/org/zeromq/TestPushPullThreadedTcp.java
src/test/java/zmq/ImmediateTest.java
src/test/java/zmq/proxy/ProxyTest.java
src/test/java/zmq/socket/pair/TestPairTcp.java
src/test/java/zmq/socket/pubsub/TestPubsubTcp.java

added tests for known fixed issues

---

src/main/java/zmq/io/net/Address.java
src/main/java/zmq/io/net/ProtocolFamily.java
src/main/java/zmq/io/net/StandardProtocolFamily.java
src/main/java/zmq/io/net/ipc/IpcAddress.java
src/main/java/zmq/io/net/tcp/TcpAddress.java
src/main/java/zmq/io/net/tcp/TcpConnecter.java
src/main/java/zmq/io/net/tcp/TcpListener.java
src/main/java/zmq/io/net/tcp/TcpUtils.java

Fix of #451 so library can be compiled with Android environment

---

src/main/java/zmq/io/Metadata.java
src/main/java/zmq/io/StreamEngine.java
src/main/java/zmq/io/mechanism/Mechanism.java
src/main/java/zmq/io/mechanism/NullMechanism.java
src/main/java/zmq/io/mechanism/curve/CurveClientMechanism.java
src/main/java/zmq/io/mechanism/curve/CurveServerMechanism.java
src/main/java/zmq/io/mechanism/plain/PlainClientMechanism.java
src/main/java/zmq/io/mechanism/plain/PlainServerMechanism.java
src/test/java/org/zeromq/TestProxy.java

Identity as bytes in metadata

---

src/main/java/zmq/io/net/tcp/TcpUtils.java

Make jeromq usable with Android API < 24

---

src/main/java/zmq/io/net/tcp/TcpUtils.java

Revert "Make jeromq usable with Android API < 24"

---

src/main/java/org/zeromq/ZProxy.java
src/main/java/zmq/util/Utils.java
src/test/java/org/zeromq/TestPushPullThreadedTcp.java
src/test/java/org/zeromq/TestZProxy.java
src/test/java/zmq/socket/reqrep/TestReqCorrelateRelaxed.java

This is an attempt to fix these tests. Attempt as there is barely no repetitivity. 
My last conclusion is that Utils.findOpenPort() does not always give correct results (and anyway its use makes tests vulnerable if a port is used between this call and bind/connect)

Fix tests randomly failing

---

src/main/java/zmq/poll/PollerBase.java
src/main/java/zmq/util/MultiMap.java
src/test/java/zmq/poll/PollEvents.java
src/test/java/zmq/poll/PollerBaseTest.java
src/test/java/zmq/poll/PollerBaseTested.java

Able to reconnect after a network loss

---

src/main/java/zmq/io/Metadata.java
src/main/java/zmq/io/net/tcp/TcpListener.java
src/main/java/zmq/poll/Poller.java
src/main/java/zmq/poll/PollerBase.java
src/main/java/zmq/util/ValueReference.java

lib now usable with Android API 10 and above.

---

src/main/java/org/zeromq/ZAuth.java
src/test/java/org/zeromq/auth/ZAuthTest.java

Added extra info for user listening to replies

---

src/main/java/zmq/socket/pubsub/Mtrie.java
src/test/java/org/zeromq/XpubXsubZTest.java
src/test/java/zmq/socket/pubsub/MTrieTest.java
src/test/java/zmq/socket/pubsub/XpubXsubTest.java

Fix removing pipe from Mtrie when using XSUB-XPUB proxy

---

src/main/java/org/zeromq/ZAgent.java
src/main/java/org/zeromq/ZAuth.java
src/main/java/org/zeromq/ZMonitor.java
src/main/java/org/zeromq/ZProxy.java
src/main/java/org/zeromq/ZStar.java
src/main/java/zmq/SocketBase.java
src/test/java/org/zeromq/ZMonitorTest.java

and added recv with timeout for ZAgent

fail-safes for ZMonitor

---

src/test/java/guide/bstarcli.java
src/test/java/guide/clone.java
src/test/java/guide/flcliapi.java
src/test/java/guide/flclient1.java
src/test/java/guide/flclient2.java
src/test/java/guide/lbbroker2.java
src/test/java/guide/lbbroker3.java
src/test/java/guide/lpclient.java
src/test/java/guide/lvcache.java
src/test/java/guide/peering1.java
src/test/java/guide/peering2.java
src/test/java/guide/peering3.java
src/test/java/guide/ppqueue.java
src/test/java/guide/ppworker.java
src/test/java/guide/spqueue.java
src/test/java/guide/tripping.java
src/test/java/org/zeromq/ParanoidPiratServerWithLazyPiratClientTest.java
src/test/java/perf/LocalLat.java

Test for #408 is a bit long (~30 sec) to perform

Test issue 408 + suppressed warnings on guides examples and perf

---

src/main/java/zmq/io/net/tcp/TcpListener.java
src/test/java/zmq/socket/pair/TestPairTcp.java

Fix binding on already used address when monitoring socket (#291)

---

CHANGELOG.md

Changelog for v0.4.3

---

src/test/java/org/zeromq/TestZLoop.java
src/test/java/zmq/PollTest.java

Test poll with channels (demonstrates #538)

---

src/main/java/org/zeromq/ZMQ.java
src/main/java/zmq/Msg.java
src/main/java/zmq/Options.java
src/main/java/zmq/ZMQ.java
src/main/java/zmq/io/Msgs.java
src/main/java/zmq/io/SessionBase.java
src/main/java/zmq/io/StreamEngine.java
src/main/java/zmq/io/mechanism/Mechanism.java
src/main/java/zmq/poll/PollerBase.java
src/main/java/zmq/util/MultiMap.java
src/main/java/zmq/util/Wire.java
src/test/java/org/zeromq/TestZMQ.java
src/test/java/zmq/HeartbeatsTest.java
src/test/java/zmq/OptionsTest.java
src/test/java/zmq/io/MsgsTest.java
src/test/java/zmq/poll/PollerBaseTest.java

I propose embedded heartbeating, should be compatible with latest libzmq on that particular regard, even if I did not test that compatibility part.
Still have some concerns about methods naming though, if anybody may give inputs it would be nice.

Heartbeat proposal (fixes #547)

---

src/test/java/org/zeromq/PubSubTest.java

Solution: add a test case based on #554

Problem: there is no test for unsubscriptions

---

pom.xml
src/main/java/org/zeromq/SocketType.java
src/main/java/org/zeromq/ZContext.java
src/main/java/org/zeromq/ZMQ.java
src/test/java/org/zeromq/TestSocketStreams.java

solution: expose stream API in ZMQ.Socket class

problem: cannot treat incoming messages as an infinite stream

---

src/main/java/org/zeromq/ZMsg.java
src/test/java/org/zeromq/ZMsgTest.java

Solution: Use builder pattern where possible

Problem: Cannot chain call on ZMsg methods

---

src/main/java/org/zeromq/ZMQ.java

As discussed in #559, this PR note stream API is in DRAFT state

note stream API is in DRAFT state

---

src/main/java/org/zeromq/ZTimer.java
src/main/java/zmq/util/Draft.java
src/main/java/zmq/util/MultiMap.java
src/main/java/zmq/util/Timers.java
src/test/java/org/zeromq/ZTimerTest.java
src/test/java/org/zeromq/guide/AsyncServerTest.java
src/test/java/org/zeromq/guide/EspressoTest.java
src/test/java/zmq/HeartbeatsTest.java
src/test/java/zmq/PollTest.java
src/test/java/zmq/util/MultimapTest.java
src/test/java/zmq/util/TimersTest.java

Solution: propose a first implementation

Problem: No Timer API in Jeromq

---

README.md
doc/exceptions.md
doc/sockets.md

Misc. README/docs fixes

---

src/main/java/org/zeromq/SocketType.java
src/main/java/org/zeromq/ZMQ.java
src/main/java/org/zeromq/ZMsg.java
src/test/java/org/zeromq/TestZContext.java
src/test/java/org/zeromq/TestZMQ.java
src/test/java/org/zeromq/ZMsgTest.java

Solution: Restore previously published APIs

Problem: various public APIs were removed or modified

---

src/main/java/org/zeromq/ZPoller.java
src/main/java/zmq/io/StreamEngine.java
src/main/java/zmq/io/mechanism/Mechanism.java
src/main/java/zmq/socket/pubsub/Mtrie.java
src/main/java/zmq/socket/pubsub/Trie.java
src/main/java/zmq/util/Z85.java

Solution: refactor the code to remove ambiguities, introduce more asserts

Problem: LGTM detected potential NPEs. Fixes #606

---

src/main/java/org/zeromq/Utils.java
src/main/java/org/zeromq/ZActor.java
src/main/java/org/zeromq/ZAuth.java
src/main/java/org/zeromq/ZCert.java
src/main/java/org/zeromq/ZCertStore.java
src/main/java/org/zeromq/ZFrame.java
src/main/java/org/zeromq/ZLoop.java
src/main/java/org/zeromq/ZMonitor.java
src/main/java/org/zeromq/ZPoller.java
src/main/java/org/zeromq/ZProxy.java
src/main/java/org/zeromq/ZStar.java
src/main/java/zmq/Ctx.java
src/main/java/zmq/Mailbox.java
src/main/java/zmq/Own.java
src/main/java/zmq/SocketBase.java
src/main/java/zmq/ZMQ.java
src/main/java/zmq/util/Utils.java
src/test/java/zmq/util/TestUtils.java

Solution: unconditional checking of arguments of public methods and constructors for org.zeromq

Problem: Arguments of public APIs are checked with asserts. Fixes #605

---

CHANGELOG.md

I've reviewed all the commits since the last release and summarized the changes for a new release. 
I propose that this release be 0.5.0, as we're dropping support for Java 7 which is a breaking change.

0.5.0 changelog notes

---

src/test/java/zmq/PollTest.java

Solution: Refactored PollTest
Fixes #621
Fixes #637

Problem: PollTest is flaky

---

src/main/java/zmq/SocketBase.java
src/main/java/zmq/io/mechanism/Mechanisms.java
src/test/java/zmq/io/mechanism/SecurityCurveTest.java
src/test/java/zmq/io/mechanism/SecurityPlainTest.java

Try to resolve issue #641, by putting checks when binding or connecting for all security mechanisms.

Adding a check of mechanisms settings.

---

src/main/java/org/zeromq/ZPoller.java

Not really important, but cleaner code.

Clean up code in ZPoller using streams and lambdas

---

src/main/java/zmq/io/StreamEngine.java

fixes #622

---

src/main/java/org/zeromq/ZContext.java

It was using a CopyOnWriteArrayList, that is not a very efficient way of
managing concurrent access. It now uses a concurrent set, created with
ConcurrentHashMap.newKeySet(). So no manual locking is needed.
linger and sndhwm was protected with a lock, I think making them volatile
provides the same semantic (immediat change of value in all threads when set)
with less code.
It slightly changes the semantic of getSockets(). I'm not sure it's very
important.
In isClosed(), a totally useless synchronized(this) is removed.

Improved concurrency of ZContext.

---

CHANGELOG.md

Just keeping our changelog notes up to date. :)

Update changelog for upcoming 0.5.0 release

---

src/main/java/org/zeromq/ZPoller.java
src/main/java/zmq/poll/PollItem.java
src/test/java/org/zeromq/TestZPoller.java

channel.
Solution: Make it possible to register multiple handlers on a single
socket or channel.
Fixes #649

Problem: Impossible to register multiple handlers for one socket or

---

src/main/java/zmq/Msg.java
src/test/java/zmq/TestMsg.java
src/test/java/zmq/TestMsgDirect.java

Solution: Fix it and test it. Fixes #682

Problem: Msg.getBytes does not return the bytes of the message.

---

src/main/java/org/zeromq/ZMQ.java
src/test/java/org/zeromq/TestZMQ.java

Solution: Introduce a new send and recv method that encode and decode
messages based on a picture pattern which is compatible to zproto.

Problem: Sending mixed data requires a lot of manual encoding

---

src/main/java/org/zeromq/ZMQ.java
src/test/java/org/zeromq/TestZMQ.java

Solution: Implement sending multiframe pictures. This does not yet
support sending string lists and hashes.

Problem: Unable to send/recv czmq compatible multiframe picture

---

pom.xml
src/main/java/org/zeromq/SocketType.java
src/main/java/org/zeromq/ZActor.java
src/main/java/org/zeromq/ZAgent.java
src/main/java/org/zeromq/ZAuth.java
src/main/java/org/zeromq/ZCertStore.java
src/main/java/org/zeromq/ZConfig.java
src/main/java/org/zeromq/ZFrame.java
src/main/java/org/zeromq/ZMQ.java
src/main/java/org/zeromq/ZMsg.java
src/main/java/org/zeromq/ZPoller.java
src/main/java/org/zeromq/ZProxy.java
src/main/java/org/zeromq/ZStar.java
src/main/java/org/zeromq/package-info.java
src/main/java/org/zeromq/util/package-info.java
src/main/java/zmq/msg/package-info.java
src/main/java/zmq/package-info.java
src/test/java/guide/ZHelper.java
src/test/java/guide/clonecli1.java
src/test/java/guide/clonecli2.java
src/test/java/guide/clonecli3.java
src/test/java/guide/clonesrv1.java
src/test/java/guide/clonesrv2.java
src/test/java/guide/clonesrv3.java
src/test/java/guide/kvsimple.java
src/test/java/guide/mdbroker.java
src/test/java/org/zeromq/TooManyOpenFilesTester.java
src/test/java/zmq/socket/reqrep/TestReqCorrelateRelaxed.java

Fixing javadoc.

---

src/main/java/org/zeromq/ZBeacon.java
src/test/java/org/zeromq/ZBeaconTest.java

Solution: Create a builder to specify an optional broadcast address
Fixes #686

Problem: ZBeacon does not provide the ability to specify server broadcast address.

---

src/main/java/org/zeromq/proto/ZNeedle.java
src/main/java/zmq/Msg.java
src/main/java/zmq/io/Msgs.java
src/main/java/zmq/io/StreamEngine.java
src/main/java/zmq/io/mechanism/Mechanism.java
src/main/java/zmq/io/mechanism/NullMechanism.java
src/main/java/zmq/io/mechanism/curve/CurveClientMechanism.java
src/main/java/zmq/io/mechanism/curve/CurveServerMechanism.java
src/main/java/zmq/io/mechanism/plain/PlainClientMechanism.java
src/main/java/zmq/io/mechanism/plain/PlainServerMechanism.java
src/main/java/zmq/util/Wire.java
src/test/java/org/zeromq/proto/ZNeedleTest.java
src/test/java/zmq/TestMsg.java
src/test/java/zmq/io/MsgsTest.java

Solution: create a new method in Msg to allow put short string prefixed
with length.

Problem: Naming of methods was confusing.

---

CHANGELOG.md

0.5.1 changelog

---

src/main/java/zmq/io/net/tcp/TcpAddress.java

Solution: Remove usages of streams and default to traditional loops.
Fixes #647

Problem: Usages of some java API forbid usage in Android

---

src/main/java/org/zeromq/ZConfig.java
src/main/java/org/zeromq/ZTimer.java
src/main/java/org/zeromq/timer/TimerHandler.java
src/main/java/org/zeromq/timer/ZTicker.java
src/main/java/org/zeromq/timer/ZTicket.java
src/main/java/org/zeromq/timer/ZTimer.java
src/main/java/org/zeromq/timer/package-info.java
src/main/java/zmq/util/MultiMap.java
src/main/java/zmq/util/Timers.java
src/test/java/org/zeromq/auth/ZConfigTest.java
src/test/java/org/zeromq/guide/AsyncServerTest.java
src/test/java/org/zeromq/timer/ZTickerTest.java
src/test/java/org/zeromq/timer/ZTicketTest.java
src/test/java/org/zeromq/timer/ZTimerTest.java
src/test/java/zmq/util/TimersTest.java

Solution: Add a ZTicket API, and ZTicker combining ZTimer and ZTicket

Problem: Timer API is still inconsistent and lacks tickets notions.

---

src/main/java/org/zeromq/timer/ZTicket.java
src/main/java/zmq/util/Timers.java
src/test/java/org/zeromq/timer/ZTicketTest.java
src/test/java/zmq/util/TimersTest.java

Solution: sort cancelled tickets at the end of the list, and remove then at the end of execution

Problem: cancelled tickets can stay in the list.

---

src/main/java/org/zeromq/ZMQ.java
src/main/java/zmq/ZMQ.java
src/main/java/zmq/socket/pubsub/XPub.java
src/test/java/zmq/socket/pubsub/XPubManualTest.java

I use libzmq(c++)  a lot and I have a Java project using XPUB. so I hope the jeromq will support XPUB more constants.

Xpub socket surpport ZMQ_XPUB_MANUAL And ZMQ_XPUB_VERBOSER constants.

---

src/test/java/guide/mdbroker.java

fix mdbroker.destory

---

src/main/java/org/zeromq/ZMQ.java

it's more readable and simpler to work with List instead of an array. it removes all the resizing and size management stuff

use simpler java collection instead of array in internal of Poller class

---

src/main/java/org/zeromq/ZMQ.java

This is another fix for #627: lambdas causing issues on Android.

Fix for #627: Poller#unregister: remove usage of lambda

---

.travis.yml
src/test/java/guide/mtrelay.java

Solution: Make the example more readable by adding an explicit Step3
instead of the main method acting as Step3

Problem: mtrelay Step3 is missing on first glance

---

scripts/prepare-android.sh
src/android/Jeromq/.gitignore
src/android/Jeromq/app/build.gradle
src/android/Jeromq/app/src/TemporaryFolderFinder.java
src/android/Jeromq/app/src/main/AndroidManifest.xml
src/android/Jeromq/build.gradle
src/android/Jeromq/gradle.properties
src/android/Jeromq/gradle/wrapper/gradle-wrapper.properties
src/android/Jeromq/gradlew
src/android/Jeromq/gradlew.bat
src/android/Jeromq/settings.gradle
src/main/java/org/zeromq/ZContext.java
src/main/java/org/zeromq/proto/ZPicture.java
src/main/java/zmq/ZMQ.java
src/main/java/zmq/io/mechanism/Mechanisms.java
src/main/java/zmq/io/net/ipc/IpcAddress.java
src/test/java/org/zeromq/HighWatermarkTest.java
src/test/java/org/zeromq/ReqRepTest.java
src/test/java/org/zeromq/TemporaryFolderFinder.java
src/test/java/org/zeromq/TestZLoop.java
src/test/java/org/zeromq/TestZPoller.java
src/test/java/org/zeromq/ZMsgTest.java
src/test/java/org/zeromq/auth/ZAuthTest.java
src/test/java/org/zeromq/auth/ZConfigTest.java
src/test/java/zmq/HeartbeatsTest.java
src/test/java/zmq/PollTest.java
src/test/java/zmq/io/net/tcp/TcpAddressTest.java
src/test/java/zmq/util/AndroidProblematic.java
src/test/java/zmq/util/TestUtils.java
src/test/java/zmq/util/TimersTest.java

Solution: Provide an android project with ability to run connected tests to assess compatibility;
Change code to make the library compatible again.
This is the first step at providing an automatic way to test compatibility with Android.
It copies all sources and test files into an Android project.
Then `./gradlew connectedAndroidTest` can be called to run the tests in a connected device.
This is crucial: compatibility issues will only be discovered when tests are run in an Android device itself.

Problem: Libray has runtime errors on Android API 16

---

CHANGELOG.md
README.md

Once this is merged, I'll deploy the next release to Maven Central.
@trevorbernard Would you mind notifying the mailing list, once the new artifact is available?

Changelog for upcoming 0.5.2 release

---

src/main/java/org/zeromq/SocketType.java
src/main/java/org/zeromq/ZFrame.java
src/main/java/org/zeromq/ZMQ.java
src/main/java/zmq/Msg.java
src/test/java/org/zeromq/ZFrameTest.java

Client/Server Socket types are now supported by a high level API

Client server zframe integration

---

src/main/java/org/zeromq/ZMQ.java

Using texts from https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/errno.h.html.
Many error number are standard posix error number.

Finishing resolve errno to String.

---

src/main/java/org/zeromq/ZCertStore.java
src/test/java/org/zeromq/ZCertStoreTest.java

Solution: Fix ZCertStore fingerprint, make tests pass
Fixes #827

Problem: ZCertStore fingerprint by timestamp is flawed

---

.circleci/config.yml
.circleci/settings.xml
pom.xml

The crosscompile profile was not working, it's doesn't override default compiler settings.
Instead two profiles are defined, the definition of the profile switch one
mode or the other.

Fixing cross compilation

---

src/test/java/org/zeromq/auth/ZAuthTest.java

Solution: add a timeout when sending a message, the authentication algorithm does not rely on the successful send
Bonus: removed deprecation annotations

Problem: ZAuthTest is flaky

---

src/main/java/org/zeromq/ZMQ.java
src/main/java/org/zeromq/ZMonitor.java
src/main/java/zmq/Ctx.java
src/main/java/zmq/SocketBase.java
src/main/java/zmq/ZMQ.java
src/test/java/org/zeromq/TestEventResolution.java

It allows to extract low level informations on the current socket, like remote IP.

Event send by monitor can now send channel to listener.

---

src/main/java/zmq/Ctx.java

Was not handling concurrency, using the hashId as the handle is not a good idea.

Many problems in the way channel were forwarded in event

---

src/main/java/org/zeromq/SocketType.java
src/main/java/org/zeromq/ZFrame.java
src/main/java/org/zeromq/ZMQ.java
src/main/java/org/zeromq/ZMsg.java
src/main/java/org/zeromq/ZThread.java
src/main/java/org/zeromq/proto/ZPicture.java
src/main/java/zmq/MailboxSafe.java
src/main/java/zmq/SocketBase.java
src/test/java/org/zeromq/ZCertStoreTest.java

new DRAFT sockets are now present in org.zeromq API

Add new socket types

---

pom.xml

problem: maven-bundle plugin has a bug on jdk15

---

src/main/java/zmq/SocketBase.java
src/test/java/zmq/TestSocketPoll.java

Solution: add poll method to the SocketBase to poll on thread safe socket

problem: No way to poll on a single thread safe socket

---

.circleci/config.yml
pom.xml

- Adding tests and build on java 17
- helping dependecies resolution by activating more profiles
- don't try to publish on forks

Fixing build

---

src/main/java/org/zeromq/ZMQ.java
src/main/java/zmq/Options.java
src/main/java/zmq/io/net/tcp/TcpUtils.java
src/main/java/zmq/socket/radiodish/Dish.java
src/main/java/zmq/socket/radiodish/Radio.java
src/main/java/zmq/util/Utils.java
src/test/java/org/zeromq/TestZMQ.java

Current snapshot was not compatible with Android API level 19. It will be changed in a future major release.

Android API level 19 compatibility

---

README.md
src/main/java/zmq/Options.java
src/main/java/zmq/io/net/tcp/TcpUtils.java
src/test/java/org/zeromq/TestZMQ.java

Keep alive handling was not really working.
Updating README.

Keep alive handling was not really working.

---

src/checkstyle/checks.xml
src/main/java/org/zeromq/ZPoller.java

Also removing IllegalImport from checkstyle, as they are handled by the android check and not matching the current API level.

ZPoller should be thread-safe.

---

pom.xml

https://dev.java/learn/modules/automatic-module/

Add Automatic-Module-Name to MANIFEST.MF

---

src/main/java/zmq/Options.java
src/main/java/zmq/ZMQ.java

This will allows client libraries to use them. I think it also make the code more explicit.

Exports all options default values as constant in ZMQ class.

---

doc/sockets.md

fix typo in doc/sockets.md

---

pom.xml

Adding known developers. Is any one missing ?

Adding developers.
