src/main/java/org/zeromq/ZFrame.java
Whether a byte stream is printable or not can be determined on finding the first ASCII value that is not printable. Without `break`, a full iteration over the byte array will be performed.
=> ZFrame.toString() – Break loop on finding the first non-printable character

src/main/java/org/zeromq/ZBeacon.java, src/main/java/org/zeromq/ZThread.java, src/main/java/zmq/Poller.java
I'm using jeromq in a situation where there is not always an opportunity to do a clean shutdown.  Because the threads are by default user threads, they cause the application to hang instead of terminating.  By setting the thread state to daemon before starting, this is no longer a problem.
Only the the thread in Poller was causing the issue in my use, but I did the same for all threads to be consistent.
=> Make java threads into daemons.

src/main/java/org/zeromq/ZBeacon.java, src/main/java/zmq/Poller.java, src/main/java/zmq/Signaler.java
To address Issue #172, signaler clear interrupted thread state right before the pipe write. Even though this, `Pipe` could still be `ClosedByInterruptException` at write and very hard to handle it.
=> Fix Spinning in Reaper Thread

src/main/java/org/zeromq/ZMQ.java, src/test/java/org/zeromq/TestProxy.java, src/test/java/org/zeromq/TestZProxy.java
ZMQ.bind method changed because is used when the port is known and  no sense return the port. Also, with this change, jeromq would have the same contract that JZMQ and ZeroMQ-Scala-Binding. Finally, most importantly, this change would use scala-zeromq library with jeromq, for now, this library only allows use with the two mentioned above libraries.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zeromq/jeromq/239)
=> Change ZMQ.bind() method to return void.

src/main/java/org/zeromq/ZLoop.java
The loop.removeTimer is called, the arg is added to the ```zombies``` list (of timers to be removed).  The zombies are removed but the ```zombies``` list is never cleared.  So they are removed at each iteration.
=> clear zombies after they are removed from timer list

src/main/java/org/zeromq/ZBeacon.java
I'm making use of jeromq in a mobile application. The application uses `ZBeacon` for service discovery but being that its a mobile application a wifi connection cannot be gauranteed. If indeed the wifi connection drops jeromq's beacon threads will have an unhandled exception when they try to send/recv over the udp sockets.
One way I have found to resolve this is to allow the application using the `ZBeacon` to set the `Thread.UncaughtExceptionHandler`s on each of the threads. Doing so lets the application catch that state and reset the beacon when wifi comes back.
A working example here:
https://github.com/kevinkreiser/lapse_app/blob/master/app/src/main/java/kevinkreiser/lapse/ServiceNode.java#L150-L157
=> Setter for uncaughtExceptionHandler in ZBeacon Threads

src/main/java/zmq/Decoder.java, src/main/java/zmq/DecoderBase.java, src/main/java/zmq/MsgAllocator.java, src/main/java/zmq/MsgAllocatorHeap.java, src/main/java/zmq/MsgAllocatorOffHeap.java, src/main/java/zmq/Options.java, src/main/java/zmq/StreamEngine.java, src/main/java/zmq/V1Decoder.java, src/main/java/zmq/ZMQ.java
MsgAllocator allows users to define how Msg are created (respectively Msg's ByteBuffer). This allows for more flexibility (e.g., this allows us to directly use DirectByteBuffers and initialize them with some extra space at their start where header information will be stored in a later step – saving us some extra copying work). 
We should probably first discuss #308 as this pull request builds on it.
=> MsgAllocator allows users to define how Msg are created

pom.xml
Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5;
2015-11-10T17:41:47+01:00) says:
'build.plugins.plugin.version' for
org.apache.maven.plugins:maven-jar-plugin is missing. It is highly
recommended to fix these problems because they threaten the stability of
your build. For this reason, future Maven versions might no longer
support building such malformed projects.
Solution: Add groupId and version to maven-jar-plugin in pom.xml
=> Problem: Building jeromq from source throws warning with maven 3.3.9

src/main/java/zmq/Mtrie.java, src/main/java/zmq/Trie.java, src/main/java/zmq/XPub.java, src/main/java/zmq/XSub.java
Fixes #323.
Addresses unnecessary byte copies when Msg contains DirectByteBuffer or HeapByteBuffers with position > 0.
=> Avoid extra byte copies in Pub/Sub 

src/test/java/guide/msreader.java
Compared with zguide msreader code, the close operation is missed?
=> receiver.close() invocation is missed in msreader example

src/main/java/org/zeromq/ZMQ.java, src/main/java/zmq/Options.java, src/main/java/zmq/Req.java, src/main/java/zmq/ZMQ.java, src/test/java/zmq/TestReqCorrelateRelaxed.java
Incidentally fixes #346.
Small note: In `testReqRecvBadRequestId()`, I had a problem where the test would hang indefinitely. It seems that the two send actions before only delivered one `ACTIVATE_READ` (I think) command to the appropriate mailbox, is that possible? Anyway, for some reason jeromq waited for a command to arrive in the mailbox, but nothing came in. I worked around it by setting a timeout on the socket.
Also, it might be that there's one or another line that my IDE formatted (although I tried to avoid any of that).
=> Implement ZMQ_REQ_RELAXED and ZMQ_REQ_CORRELATE sockopts

src/main/java/zmq/Req.java
That API is only compatible with Java 8. (This replaces #367)
=> Stop using java.time API

src/checkstyle/checks.xml, src/main/java/org/zeromq/ZContext.java, src/main/java/org/zeromq/ZFrame.java, src/main/java/org/zeromq/ZMQ.java, src/main/java/org/zeromq/ZMQException.java, src/main/java/org/zeromq/ZThread.java, src/test/java/org/zeromq/TestZMQ.java
- fixed npe and mangling of existing indexes in ZMP.Poller (code synced with jzmq which does not have this issue)
- fixed windows bug in Signaler (reverted change introduced in 0.3.5)
- fixed failing tests on windows
- small changes to sync with jzmq
=> A number of fixes, most ported from jzmq

src/main/java/org/zeromq/ZFrame.java, src/main/java/org/zeromq/ZMQ.java, src/main/java/org/zeromq/ZMQException.java, src/main/java/org/zeromq/ZThread.java
The codebase is failing the current checkstyle rules, preventing `mvn install` (and other commands, I assume) from working.  This fixes all those style rule failures.
=> Whitespace changes to make the style checker happy

src/main/java/org/zeromq/ZContext.java, src/main/java/org/zeromq/ZMQ.java, src/main/java/zmq/Ctx.java, src/main/java/zmq/ZMQ.java, src/test/java/org/zeromq/TestReqRouterThreadedTcp.java, src/test/java/org/zeromq/TestZContext.java, src/test/java/zmq/TooManyOpenFilesTester.java
This PR picks up where #230 left off. The goal of this is to ensure that polling Selector resources are deallocated, in order to avoid "Too many open files" problems.
- I started with #230 and rebased on top of current master. There were no conflicts to resolve. I did have to update the ZMQ static method names in @fredoboulo 's new test file, as the method names had changed in master since he opened his PR.
- Per @trevorbernard 's suggestion, I un-reverted the fix in https://github.com/zeromq/jeromq/commit/4a19a453645d9c584345cb24868e9ff9b1fe02bd. I don't understand the full context, but it seems to me like this was fixed for a reason, and it's generally good for our code to be faithful to libzmq code. @trevorbernard also noted that shutdown would hang without that fix.
- There was a test …
=> Allow ZMQ.Context / ZContext to manage closing poll selectors

src/main/java/org/zeromq/Utils.java, src/main/java/zmq/Utils.java, src/test/java/org/zeromq/TestProxy.java, src/test/java/org/zeromq/TestReqRouterThreadedTcp.java, src/test/java/org/zeromq/TestZMQ.java, src/test/java/org/zeromq/TestZProxy.java, src/test/java/org/zeromq/ZBeaconTest.java, src/test/java/org/zeromq/ZSocketTest.java, src/test/java/zmq/TcpAddressTest.java, src/test/java/zmq/TestConnectDelay.java, src/test/java/zmq/TestConnectResolve.java, src/test/java/zmq/TestLastEndpoint.java, src/test/java/zmq/TestMonitor.java, src/test/java/zmq/TestPairTcp.java, src/test/java/zmq/TestProxyTcp.java, src/test/java/zmq/TestPubsubTcp.java, src/test/java/zmq/TestReqrepDevice.java, src/test/java/zmq/TestReqrepTcp.java, src/test/java/zmq/TestRouterHandover.java, src/test/java/zmq/TestRouterMandatory.java, src/test/java/zmq/TestShutdownStress.java, src/test/java/zmq/TestSubForward.java, src/test/java/zmq/TestTermEndpoint.java, src/test/java/zmq/TooManyOpenFilesTester.java
This makes the tests more deterministic by not using hard-coded ports that might already be in use by another process on your computer. I've noticed tests failing both on my machine and in Travis builds for this reason. Instead, we can use the ServerSocket constructor (wrapped up in a new util method, `findOpenPort`) to find ports that are guaranteed to be available.
Fixes #385.
=> Ensure that the tests always use ports that aren't already in use

src/main/java/org/zeromq/ZMQ.java, src/main/java/zmq/Ctx.java
This should fix #380 (Destroying a context while polling causes java.nio.channels.ClosedChannelException).
Summary of changes in this PR:
- When a Poller is created via a context (which is the recommended way to do it; see #386), `poller.context` is set to that context so the poller has a reference to it.
- When `poll` results in a ClosedChannelException or any other ZError.IOException, we check to see if the context is terminated, and if so, we catch the exception and return 0.
=> When polling and the context is terminated, don't throw ZError.IOException

src/main/java/org/zeromq/ZContext.java, src/main/java/zmq/Ctx.java, src/main/java/zmq/Reaper.java
This PR picks up where #274 left off.
Summary of changes:
- **ZContext**
- Make the parameters set in the constructor final, and deprecate the setters for those parameters:
- setIoThreads
- setMain
- setContext
- Because it is no longer possible for the setters to set these parameters (results in a compile error), the deprecated setters are now no-ops. Any code utilizing these functions should be rewritten, which I think is a step in the right direction.
- **Ctx**
- Move the code block for initialization of slots to a separate function, to reduce the size of createSocket(). (aesthetic change only)
- **Reaper**
- Move duplicated code block to a function. (aesthetic change only)
- Increment reap count before starting the reap instead of after.
=> Minor refactoring in ZContext, Ctx, Reaper

CHANGELOG.md
Fixes #371.
I went through https://github.com/zeromq/jeromq/compare/v0.3.5...v0.3.6 and reviewed all the changes and added a summary of the changes.
This is what I think we should do, going forward. It's much more useful than an unorganized dump of the commit messages.
=> Add version release dates; add 0.3.6 release notes

src/test/java/guide/bstarcli.java, src/test/java/guide/lpclient.java
In #386, I moved the poller initialization code in these ZGuide examples up above the while loop, so that we're re-using the same poller instead of creating a new one on each iteration.
This broke the examples because of the retry pattern where we're destroying and re-creating the sockets that are being polled. When the poller polls again, it polls a socket that has been destroyed, resulting in a ClosedChannelException.
This PR fixes that by unregistering the socket that gets destroyed and registering the new one.
=> Fix use of pollers w/ sockets that get destroyed in examples

src/main/java/zmq/TcpListener.java
simple fix for #412 . i am only changing 1 private method (`TcpListener::accept`). that method is only used in one place.  i am changing the method to throw an `IOException` instead of returning null.  returning null is guaranteed to cause a `NullPoinerException` which is guaranteed to stop the `Poller::run` loop.  an `IOException` will instead be caught by an existing catch block in `TcpListener::acceptEvent` and handled gracefully (sent to the monitor socket or ignored).
=> #412 tcp accept filter null pointer exception fix

CHANGELOG.md
i've added a 0.4.1 release to the changelog.  this is also my way of asking for a release build, though i can open an issue ticket if that's better. i realize you just cut a release a couple weeks ago, but that means your machine is already set up to do it again, right? :)
=> #413 ZMQ.ZMQ_TCP_ACCEPT_FILTER NullPointerException fix changelog update

src/main/java/org/zeromq/ZMQ.java
These are very minor non-functional changes that correct a few erroneous javadoc references to methods that were previously moved or had their signature changed.
=> Fix erroneous javadoc references in ZMQ

src/main/java/org/zeromq/ZBeacon.java, src/main/java/zmq/poll/Poller.java
I read [this](http://www.yegor256.com/2015/10/20/interrupted-exception.html) today and learned about how to properly handle an InterruptedException. Because of #116, I was curious to see if there are any places in the codebase where we aren't doing this the right way, and I think I found two places where we are swallowing an InterruptedException.
I don't think this fixes #116, but I believe this to be a step in the right direction. Perhaps the problem re: #116 is that we aren't checking `Thread.interrupted()` often enough in the low-level code. I'm still trying to figure that one out.
=> Poller.destroy: don't swallow InterruptedException

src/test/java/org/zeromq/DealerDealerTest.java
This test passed several times on my machine but fails in CI. Relooking at it, the use case seems legit (no loss of message on disconnection/reconnection) but too error-prone in its current form
=> Disable test until fix

src/main/java/zmq/Options.java, src/test/java/zmq/io/mechanism/SecurityCurveTest.java
When setting the CURVE keys for ZMQ.Sockets the given byte array was parsed as a String although it already contained the raw key bytes.
This caused our application to fail because it was not clear that the byte arrays created by the Curve.keypair()-method were not allowed to be used directly. 
Instead we head to create Z85 encoded Strings and get their byte value UTF-8. This PR fixed this behaviour.
Also added a regression test for this bug.
=> Do not parse CURVE keys as Strings

src/main/java/zmq/io/net/tcp/TcpUtils.java
Reverts zeromq/jeromq#458 to reinstate possibility to use lib in Android environment, as the failing tests are fixed.
=> Revert "Revert "Make jeromq usable with Android API < 24""

src/main/java/org/zeromq/ZActor.java, src/main/java/org/zeromq/ZBeacon.java, src/main/java/org/zeromq/ZMQ.java, src/main/java/org/zeromq/ZPoller.java, src/main/java/org/zeromq/ZProxy.java, src/main/java/zmq/io/SessionBase.java, src/main/java/zmq/socket/FQ.java
Assert on FQ to assess single-threading behavior on receive (related to #447)
ZMQ.Socket class is no longer final (fixes #446)
added jacoco coverage as a proposal
Small javadoc changes
Handle interrupt by close in ZBeacon (quite rare occurrences)
=> Small changes

src/main/java/org/zeromq/ZBeacon.java, src/test/java/org/zeromq/ZBeaconTest.java
Added test for ignoring own beacons in ZBeacon regarding #296 , but disabled as they fail in Travis.
Added boolean parameter in ZBeacon to allow configure blocking behaviour of Datagram Socket, to provide reporters of #318 an handy way to solve their situation.
=> Added option to configure datagram socket blocking behaviour

pom.xml, src/main/java/org/zeromq/ZAuth.java, src/main/java/org/zeromq/ZMQ.java, src/main/java/org/zeromq/ZMonitor.java, src/main/java/org/zeromq/ZStar.java, src/main/java/zmq/Proxy.java, src/main/java/zmq/SocketBase.java, src/main/java/zmq/ZMQ.java, src/main/java/zmq/socket/pubsub/Mtrie.java, src/main/java/zmq/socket/pubsub/Trie.java, src/main/java/zmq/socket/pubsub/XPub.java, src/main/java/zmq/socket/pubsub/XSub.java, src/test/java/org/zeromq/TestProxy.java, src/test/java/org/zeromq/XpubXsubZTest.java, src/test/java/org/zeromq/ZMonitorTest.java, src/test/java/org/zeromq/auth/ZAuthTest.java, src/test/java/org/zeromq/util/ZDataTest.java, src/test/java/zmq/proxy/ProxySingleSocketTest.java, src/test/java/zmq/proxy/ProxyTerminateTest.java, src/test/java/zmq/proxy/ProxyTest.java, src/test/java/zmq/socket/pubsub/MTrieTest.java, src/test/java/zmq/socket/pubsub/TrieTest.java, src/test/java/zmq/socket/pubsub/XpubXsubTest.java
Coverage can be activated with given profile, aka mvn clean package -Pcoverage.
This leads to other changes, to improve code coverage.
In particular, Mtrie and Trie are now with 87 and 92% coverage.
Method signatures have also been changed to avoid extra copy of array when dispatching message from XPUB and XSUB.
Final changes: org.zeromq.ZMQ constants are referring to zmq ones, and handy constants for messages to controlled proxy were introduced.
=> Added optional jacoco coverage

.travis.yml, README.md, pom.xml
For #472.
I tried running `mvn clean test jacoco:report coveralls:report -P coverage` locally and it works except for the Coveralls part. I did some reading on this, and it looks like if we ever want to run the Coveralls submit task locally, we need to include `-DrepoToken=coverallsrepotokengoeshere`, per the Coveralls Maven plugin README.
I wasn't able to test that part because I don't have admin access to the JeroMQ repo, therefore I cannot see the repo token in the Coveralls UI, [as noted here](https://github.com/lemurheavy/coveralls-public/issues/152#issuecomment-33510656).
On the other hand, Travis should be able to start submitting coverage reports to Coveralls out-of-the-box, from what I've read, so hopefully this will just work™ when this PR is merged and Travis runs on the master …
=> Add Coveralls Maven plugin and Travis CI integration

CONTRIBUTING.md
See my comment at the end of issue #4, which I took the liberty of closing.
To summarize, I don't think it is necessary for new contributors to leave a comment on issue #4 stating that they have read and understand the C4 process. Case in point, the vast majority of contributors have not done this, and it hasn't been a problem. Of course I'm not arguing that we shouldn't follow the C4 process, it just seems silly to ask people to state that they are going to adhere to it.
I believe it is sufficient that we have detailed information about the contribution process, and we trust that contributors follow the process.
=> Remove link to issue #4 in CONTRIBUTING.md

src/main/java/zmq/socket/reqrep/Req.java, src/test/java/zmq/Helper.java, src/test/java/zmq/socket/reqrep/TestReqRelaxed.java
Problem: it is not possible to send two messages in a row without a successful receive in between, with a REQ socket in RELAXED mode.
Backport of https://github.com/zeromq/libzmq/issues/1690 fix that was not present in libzmq/4.1
Fix for the first part of #442, issue may still not be resolved fully.
=> Sending 2 messages in a row on REQ socket with ZMQ_REQ_RELAXED option

src/main/java/zmq/io/coder/DecoderBase.java, src/test/java/zmq/io/AbstractProtocolVersion.java, src/test/java/zmq/io/V0ProtocolTest.java, src/test/java/zmq/io/V1ProtocolTest.java, src/test/java/zmq/io/V2ProtocolTest.java
Fix #497.
I added some tests (obviously) for protocols except V3 (which is now used in every other test). May you make a review of the tests messages format?
=> Problem: No communication with libzmq 2.2.0

src/main/java/zmq/ZMQ.java, src/main/java/zmq/util/Clock.java
I ran into a situation today where Poller#poll was blocked for a long time even though a timeout value of 1 second had been passed to poll. I attached a debugger and captured the state displayed in the attached screenshot. As you can see `waitMillis` has a value of just over an hour even though `timeout` is set to 1000.
This can happen because `poll` uses `currentTimeMillis` values to measure elapsed time without taking into account that the system clock may be changed in the meantime.
To avoid this I've updated `poll` to use `nanoTime` instead. This way elapsed time is measured correctly regardless of system time changes.
=> Avoid using system time to measure elapsed time

src/test/java/org/zeromq/TestRapidOpenCloseSocket.java
In the interest of working toward a solution to #198, I copied @augustl's code into a new test file and patched it up a little bit to work with the current state of JeroMQ.
I basically just replaced the `ZMQ.context(1)` with a `new ZContext()` and replaced the context methods with the corresponding methods from ZContext (e.g. `ctx.socket` became `ctx.createSocket`, `ctx.term` became `ctx.destroy`).
I also removed the lines near the end that manually close the sockets, as this is something that the ZContext does for you when it is terminated.
Rather than use the same port every time, I used `Utils.findOpenPort` to use a new available port on every run, so we can at least conclude that the issue isn't something to do with reusing the same port.
I was able to reproduce the issue easily -- …
=> Add a (failing) test for issue #198

src/main/java/zmq/poll/PollerBase.java, src/main/java/zmq/util/MultiMap.java, src/test/java/zmq/poll/PollerBaseTest.java, src/test/java/zmq/socket/pair/TestPairIpc.java
Please have a look at the tests to assess if the described behaviour is as expected.
=> Fix #534: If timer is cancelled, it should not be executed again without being readded

src/main/java/org/zeromq/ZContext.java, src/test/java/org/zeromq/TestZContext.java
Fixes #545.
Given a ZContext `ctx`, I don't think it ever makes sense for `ctx.getContext()` to be `null`. Currently, however, we are creating the internal ZMQ.Context lazily whenever `getContext()` is called. This causes unexpected behavior because `ctx.isClosed()` initially returns `true` (hence #545).
We are also setting the reference to the internal context to `null` after terminating the ZMQ.Context when the ZContext is closed. This is even worse, because if another thread happens to try to use the ZContext after it's closed, a new ZMQ.Context ends up secretly being created.
This PR solves both problems by creating the ZMQ.Context as part of the ZContext constructor, and never setting it to null. When a ZContext is destroyed, the internal ZMQ.Context is terminated, and any further …
=> Initialize the internal ZMQ.Context of a ZContext only when creating it

README.md, doc/contexts.md, doc/exceptions.md, doc/pollers.md, doc/security/curve.md, doc/sockets.md, src/test/java/guide/hwserver.java
Closes #541.
I don't claim to be an authority on JeroMQ by any means, but I've documented what I know. Hopefully this addresses the specific questions raised in #541 by @fbacchella, and can serve as a good starting point for the project to have nice, user-friendly documentation.
NB: I considered putting this information in the Javadocs, but it occurred to me that Javadocs are organized by packages and classes, which doesn't give us a good place to document general ideas about ZeroMQ and JeroMQ. For this reason, I think it's better to have a canonical "docs" folder where we can organize things in a more intuitive way.
Feedback welcome!
=> First cut of "getting started" documentation

src/main/java/zmq/socket/reqrep/Req.java, src/test/java/zmq/HeartbeatsTest.java
Solution: ignore command messages in the REQ session to avoid
disrupting the state machine.
Commands are handled by the engine before handing off to the session.
Fixes #551
=> Problem: HEARTBEAT command breaks REQ connection

README.md, src/main/java/org/zeromq/ZMQ.java, src/main/java/org/zeromq/package-info.java, src/main/java/org/zeromq/util/package-info.java, src/main/java/zmq/msg/package-info.java, src/main/java/zmq/package-info.java, src/main/java/zmq/util/Draft.java
As a possible outcome of #548 and #536, javadocs and README are updated. Most of the comments have been taken from http://api.zeromq.org/4-1:_start.
In addition, a @Draft annotation has been introduced to hopefully differentiate stable API from experimental ones. Annotation is far away from perfect, and should be together with appropriate comments, but that's a first start.
=> #548: javadoc update

src/main/java/zmq/SocketBase.java, src/main/java/zmq/io/net/Address.java, src/main/java/zmq/io/net/ipc/IpcAddress.java, src/main/java/zmq/io/net/ipc/IpcListener.java, src/main/java/zmq/io/net/tcp/TcpAddress.java, src/main/java/zmq/io/net/tcp/TcpListener.java, src/main/java/zmq/util/Utils.java, src/test/java/zmq/TermEndpointIpcTest.java, src/test/java/zmq/TestLastEndpoint.java, src/test/java/zmq/TestTermEndpoint.java, src/test/java/zmq/util/TestUtils.java
Solution: implement wildcard binding for ipc and tcp protocol, using LAST_ENDPOINT to retrieve the dynamically allocated endpoint.
=> Problem: Utils.findOpenPort() is not the most reliable method in the world (#563)

src/main/java/org/zeromq/ZMQ.java
The errno was set to 48 while trying to connect to a port in use. Additional usage of that socket causes an exception being raised if this errno is not set back to 0.
=> Fixed #577 - "ZMQException: Address already in use"

src/main/java/zmq/SocketBase.java, src/main/java/zmq/socket/Pair.java, src/main/java/zmq/socket/Stream.java, src/main/java/zmq/socket/pipeline/Pull.java, src/main/java/zmq/socket/pipeline/Push.java, src/main/java/zmq/socket/pubsub/Pub.java, src/main/java/zmq/socket/pubsub/XPub.java, src/main/java/zmq/socket/pubsub/XSub.java, src/main/java/zmq/socket/reqrep/Dealer.java, src/main/java/zmq/socket/reqrep/Router.java, src/test/java/zmq/ConnectRidTest.java, src/test/java/zmq/Helper.java
Due to a race condition between receiving connections on the io thread and the call to socket.connect(), ZMQ_CONNECT_RID can be assigned to the wrong peer socket.
I recently fixed the same bug in the [libzmq](https://github.com/zeromq/libzmq/issues/3191) implementation. You can see more details there.
=> Race condition with received message causes ZMQ_CONNECT_RID to be assigned to wrong socket

src/main/java/zmq/Ctx.java, src/test/java/org/zeromq/TestZContext.java, src/test/java/zmq/CtxTest.java
If a second socket connects on the same address, the first one is lost
and cannot be closed thereafter.
Solution: use a MultiMap to store collection of pending connections per address
=> Problem: pending connections are unique per address. (fixes #595)

src/main/java/zmq/io/StreamEngine.java
Problem: the method `StreamEngine::restartInput(). issue #604
Solution:: Simplify the method - 
by inlining temp variables and extracting another decoding helper method.
I work on semi-automatic refactoring pull requests.
If you think this project will benefit from refactoring PRs, please click the link below.
[![Yes - I want a refactoring service](http://box2110.temp.domains/~refacto3/wp-content/uploads/2018/09/yes-e1537456577294.jpeg)](http://box2110.temp.domains/~refacto3/refactoring-pull-requests-yes/)
If this PR annoys you, please click on the link below, so I will stop doing it in other repos as well
[![No please - it annoys me](http://box2110.temp.domains/~refacto3/wp-content/uploads/2018/09/no-e1537456561421.jpeg)](http://box2110.temp.domains/~refacto3/free-refactoring-pull-request …
=> Simplify the method restartInput() in the class StreamEngine

src/main/java/org/zeromq/ZMQ.java, src/main/java/zmq/Options.java, src/main/java/zmq/ZMQ.java, src/main/java/zmq/io/net/SelectorProviderChooser.java, src/main/java/zmq/io/net/tcp/TcpConnecter.java, src/main/java/zmq/io/net/tcp/TcpListener.java, src/test/java/org/zeromq/SelectorProviderTest.java, src/test/java/zmq/OptionsTest.java
I added a way to define custom SelectorProvider (https://docs.oracle.com/javase/8/docs/api/java/nio/channels/spi/SelectorProvider.html). It should allow to wrap socket with custom code, like flow compression or TLS, using for example https://github.com/marianobarrios/tls-channel.
Any feedback is welcome.
=> A SelectorProvider

src/main/java/zmq/Signaler.java
32-bit integer cursors in Signaler can overflow within a month or so under high load, and causes serious problems.
When wcursor in Signaler overflows, waitEvent(timeout == 0) cannot return true until recv() is called so that rcursor overflows as well. This condition is particularly harmful to IOThread, as it irreversibly renders IOThread unable to retrieve commands from its mailbox in inEvent(), because mailbox never calls any other methods in Signaler until it gets true from waitEvent() and IOThread always specifies timeout == 0 for mailbox.recv(). This in turn causes serious problems, such as a server being unable to accept new client connections anymore.
This pull request replaces 32-bit integer cursors with 64-bit long cursors. It does not fix the problem 100%, but fixes it within …
=> Change cursors in Signaler to long to avoid overflowing

src/main/java/zmq/io/mechanism/Mechanism.java, src/main/java/zmq/io/mechanism/NullMechanism.java, src/main/java/zmq/io/mechanism/curve/CurveClientMechanism.java, src/main/java/zmq/io/mechanism/curve/CurveServerMechanism.java, src/main/java/zmq/io/mechanism/plain/PlainServerMechanism.java
=> Remove puts debugging method.

src/main/java/zmq/Signaler.java
This stack trace is never lost, it's stored in a wrapping exception.
All the other one I found in this class needs special handling.
=> Removing a really redundant stack trace, as the exception is returned.

src/main/java/org/zeromq/ZSocket.java, src/main/java/zmq/ZMQ.java
Since java 1.7, Charset.forName is clunky for a few standards charsets
like UTF-8. This patch uses StandardCharsets.UTF_8 instead and reuse ZMQ.CHARSET.
=> Improving usage of charset UTF-8

src/main/java/zmq/Signaler.java
In Signaler.waitEvent:
When selector.select(0) return 0 and there is indeed keys it means that
this method was interrupted, not to try again. So set errno to EINTR.
=> Improved Signaler interrupt handling.

src/main/java/org/zeromq/ZMQ.java, src/main/java/zmq/ZError.java
Now all the declared error code in zmq.ZError are now in the Error enum.
It centralized the error message too, it make adding new messages easier.
=> Improved org.zeromq.ZMQ.Error enum

src/main/java/org/zeromq/ZPoller.java, src/main/java/org/zeromq/ZStar.java, src/main/java/zmq/ZMQ.java, src/main/java/zmq/io/net/tcp/SocksConnecter.java, src/main/java/zmq/io/net/tcp/TcpConnecter.java, src/main/java/zmq/io/net/tipc/TipcListener.java
- unused attributes.
- unused private methodes.
- annotation for the call of a necessary deprecated method.
=> Removing some warning:

src/main/java/org/zeromq/ZMQ.java, src/main/java/zmq/Ctx.java, src/main/java/zmq/SocketBase.java, src/main/java/zmq/ZMQ.java
It's should be a boolean and it's really a flag that they object is active instead.
=> Removed the tag field in zmq.Ctx and zmq.SocketBase

doc/development/public-keys.md, doc/development/release.md
* Moved the document into a `development` subfolder of the `doc` folder.
* Fixed link to an example of a JIRA issue requesting access to `org.zeromq/jeromq`.
* To make the doc shorter, moved @trevorbernard 's public key into a new file containing a list of known public keys that have been used to sign JeroMQ releases.
* I went ahead and added myself to that list, since I'll be deploying releases from here on.
=> Release documentation edits

src/main/java/zmq/io/StreamEngine.java
The allocation of decoder or encoder could faild if given a wrong class, but
in this it will return null and print a stack. It now return ZError.InstantiationException.
But it can also throw a more classical IllegalArgumentException. It also
use generic instead of type cast.
=> The StreamEngine didn't handle well instantiation failure

src/main/java/zmq/Options.java, src/main/java/zmq/ZError.java, src/test/java/zmq/io/coder/CustomDecoderTest.java, src/test/java/zmq/io/coder/CustomEncoderTest.java
All the check were done using assert, that are disable during runtime,
make the whole method useless. It was printing result to stdout, this is
bad practice. It now use ZError.InstantiationException. The check method
name is more explicit too.
The CustomDecoderTest is updated, and warning removed, because it used
deprecated methods.
It also add a case where ZError.InstantiationException better match the
source exception.
=> custom decoder check was invalid

src/main/java/zmq/Mailbox.java
This was not checked, cpipe.read will return null, active will be set.
I'm not sure that is a an expected state, and the assert make my tests fails.
=> in zmq.Mailbox, a call to Signaler.recv could set errno to EINTR

src/main/java/org/zeromq/UncheckedZMQException.java, src/main/java/org/zeromq/ZMQException.java, src/main/java/zmq/ZError.java
All exceptions from jeromq are unchecked exception, it's not possible which one will be thrown but a method. So I have all other my code catches like:
```java
catch (ZError.IOException | ZError.CtxTerminatedException | ZError.InstantiationException | ZMQException ex)
```
Having a single exception catched will make code more readable and less error-prone. It will also make possible for jeromq to add exception.
I also wrote some code to transform jeromq's unchecked exception in checkedexception, it make exception handling more robust I think, I don't know if you find it intersting:
```java
import java.io.IOException;
import java.net.SocketException;
import java.nio.channels.ClosedByInterruptException;
import java.nio.channels.ClosedChannelException;
import org.zeromq.ZMQ;
import …
```
=> Define a common parent class for all ZMQ exceptions

src/test/java/org/zeromq/TestZContext.java, src/test/java/zmq/ImmediateTest.java, src/test/java/zmq/TestConnectDelay.java, src/test/java/zmq/TestTermEndpoint.java
The following tests were failing randomly:
- TestConnectDelay
- ImmediateTest
- test that inherit from TestTermEndpoint
- TestZContext could randomly hang, at least it will timeout
=> Improving some tests reliability

src/main/java/zmq/poll/PollerBase.java
During my work, I found failed connection retry will make the member 'timer' of PollerBase larger and larger, while the remaining list were all empty and would never be used. So remove them to reduce the memory usage.
=> Remove empty timer list

src/test/java/zmq/io/net/TestAddress.java, src/test/java/zmq/io/net/tcp/TcpAddressTest.java
As I noted in https://github.com/zeromq/jeromq/issues/704#issuecomment-479505302, these tests are failing on my machine, as presumably my ISP provides a fallback IP when resolving nonexistent addresses.
Since we can't rely on the address resolution available in the environment used to run the tests, I don't think we can really test the "sad path" of attempting to resolve a supposedly invalid address. So, we should just remove these tests, at least for now, to unblock releasing JeroMQ 0.5.1. (see #704)
=> Remove unreliable test cases about resolving supposedly invalid addresses

src/test/java/zmq/io/net/TestAddress.java, src/test/java/zmq/io/net/tcp/TcpAddressTest.java
This is a follow up to #706 based on @fbacchella 's comment on https://github.com/zeromq/jeromq/issues/704#issuecomment-479560401
I was able to get both of the problematic tests passing by using a known valid domain and known invalid subdomain. So, I think we can re-add the tests with this improvement.
=> Improve sad path address resolution tests

src/test/java/org/zeromq/ZBeaconTest.java
Fixes #620 and gets us closer to releasing JeroMQ 0.5.1. (see #704)
This is not totally great because it means we aren't testing the fix for #686 where ZBeacon supports using 255.255.255.255 as a broadcast address. Feedback welcome.
=> ZBeaconTest: use 127.0.0.1 instead of 255.255.255.255 to get tests passing

doc/development/release.md, pom.xml
I think I just succeeded in deploying JeroMQ 0.5.1 to OSSRH and releasing to Maven Central, all from the command line, guided by this [somewhat confusing release plugin documentation](https://central.sonatype.org/pages/apache-maven.html).
Hopefully we'll see version 0.5.1 show up [here](https://mvnrepository.com/artifact/org.zeromq/jeromq) within the next 10 hours or so.
This process has been a little bit confusing. I think I've correctly documented the process that I followed, but I'm only like 90% sure, so take it with a grain of salt.
Whenever we release the next version, I'll follow my own instructions here and fix anything that's wrong.
=> Update release docs

.travis.yml
Hopefully this will make it so that we have 4 builds:
* Java w/ OpenJDK 8
* Android w/ OpenJDK 8
* Java w/ Oracle JDK 8
* Android w/ Oracle JDK 8
Right now we just have the first two.
=> Travis build tweaks, pt. 2

.travis.yml
This should make our Travis builds faster -- should be interesting to see by how much.
=> Speed up Travis build by caching Maven dependencies

src/main/java/org/zeromq/ZCert.java, src/main/java/org/zeromq/ZConfig.java
Solution: provide a save method with a writer in input.
Fixes #690
=> Problem: ZCert can only be saved on a file.

src/main/java/org/zeromq/ZSocket.java, src/test/java/org/zeromq/TestPushPullThreadedTcp.java, src/test/java/org/zeromq/ZSocketTest.java
Problem: lack of constructor with SocketType enum in ZSocket
Solution: create a new constructor accepting SocketType enum
it's an improvement on ZSocket API regarding #394.
=> Create a new constructor accepting SocketType enum

src/main/java/zmq/Msg.java, src/test/java/zmq/TestMsg.java
As discussed in https://github.com/zeromq/jeromq/issues/638#issuecomment-508792276 the bug of wrong buffers returned by `Msg#recv` can be fixed by removing the (mostly redundant) `data` field from the `Msg` class.
The bug was found with buffers allocated through `ByteBuffer.allocateDirect()` on Android, but the same problems occur with regular buffers obtained from `ByteBuffer#slice()` (any buffer that doesn't fully use its backing array can cause problem). The proposed change includes 5 tests that fail in the current version but are fixed here (the `slice()` method is used to emulate the Android buffer allocation).
This also fixes the bug where `Msg#get()` and `Msg#getBytes()` give inconsistent results (see https://github.com/zeromq/jeromq/issues/638#issuecomment-508792276 ).
Note that …
=> Fix #638: remove data field from zmq.Msg

pom.xml
Source: https://snyk.io/vuln/SNYK-JAVA-COMPUPPYCRAWLTOOLS-543266
I found that the maven checkstyle plugin also needed to be upgraded from 3.0.0 => 3.1.0 because of an API incompatibility issue.
`mvn verify` completes successfully with this change.
=> Upgrade checkstyle dependencies to fix vulnerability

pom.xml, src/main/java/org/zeromq/ZMQ.java, src/main/java/org/zeromq/proto/ZPicture.java, src/main/java/zmq/io/net/tcp/TcpAddress.java
As I was releasing 0.5.2, I noticed some javadoc warnings:
```
[INFO] Note: Custom tags that could override future standard tags:  @apiNote. To avoid potential overrides, use at least one period character (.) in custom tag names.
[INFO] 7 warnings
[INFO] [WARNING] Javadoc Warnings
[INFO] [WARNING] /home/dave/code/jeromq/target/checkout/src/main/java/org/zeromq/ZMQ.java:833: warning - Tag @link: can't find Socket(Context, SocketType) in org.zeromq.ZMQ.Socket
[INFO] [WARNING] /home/dave/code/jeromq/target/checkout/src/main/java/org/zeromq/ZMQ.java:2213: warning - @param argument "chooser," is not a parameter name.
[INFO] [WARNING] /home/dave/code/jeromq/target/checkout/src/main/java/org/zeromq/ZStar.java:169: warning - Tag @link: can't find create(ZContext, Socket, int, Star, Object...) in …
```
=> Upgrade maven-javadoc-plugin; fix a few javadoc warnings

src/main/java/org/zeromq/timer/ZTicket.java, src/test/java/org/zeromq/timer/ZTickerTest.java
Fix a bug when ticket timeout less than zero
=> Fix a bug when ticket timeout less than zero

src/main/java/org/zeromq/ZMQ.java, src/main/java/zmq/Ctx.java, src/main/java/zmq/Options.java, src/main/java/zmq/SocketBase.java, src/main/java/zmq/ZMQ.java, src/main/java/zmq/io/HelloMsgSession.java, src/main/java/zmq/socket/Sockets.java, src/main/java/zmq/socket/reqrep/Dealer.java, src/main/java/zmq/socket/reqrep/Rep.java, src/main/java/zmq/socket/reqrep/Req.java, src/main/java/zmq/socket/reqrep/Router.java, src/test/java/zmq/TestHelloMsg.java
When using ZMQ_HEARTBEAT one still needs to implement application-level heartbeat in order to know when to send a hello message.
For example, with the majordomo protocol, the worker needs to send a READY message when connecting to a broker. If the connection to the broker drops, and the heartbeat recognizes it the worker won't know about it and won't send the READY msg.
To solve that, the majordomo worker still has to implement heartbeat. With this new option, whenever the connection drops and reconnects the hello message will be sent, greatly simplify the majordomo protocol, as now READY and HEARTBEAT can be handled by zeromq.
Port of https://github.com/zeromq/libzmq/pull/3870
=> problem: ZMQ_HEARTBEAT is not useful without sending an hello message

src/main/java/org/zeromq/ZContext.java
If a socket failed during close, it's not removed from ZContext, even
if it should.
=> Resolve #776.

src/main/java/org/zeromq/ZActor.java, src/main/java/org/zeromq/ZContext.java, src/main/java/org/zeromq/ZMQ.java, src/main/java/org/zeromq/ZProxy.java, src/test/java/guide/bstarcli.java, src/test/java/guide/clonesrv6.java, src/test/java/guide/espresso.java, src/test/java/guide/flclient1.java, src/test/java/guide/lpclient.java, src/test/java/guide/mdcliapi.java, src/test/java/guide/mdcliapi2.java, src/test/java/guide/mdwrkapi.java, src/test/java/guide/ppworker.java, src/test/java/org/zeromq/ParanoidPiratServerWithLazyPiratClientTest.java, src/test/java/org/zeromq/TestPushPullThreadedTcp.java, src/test/java/org/zeromq/TestReqRouterThreadedTcp.java, src/test/java/org/zeromq/TestZContext.java, src/test/java/org/zeromq/auth/ZAuthTest.java, src/test/java/zmq/OptionsTest.java
The ZContext used to create a ZMQ.Socket is now stored within the socket. So with this patch, socket.close() is now enough to remove the socket from the internal state of ZContext.
It makes the use of try-with-resources much easier.
It also remove the unused Ctx storage from  ZMQ.Socket.
=> ZMQ.Socket now remember the ZContext that created it

src/main/java/zmq/Ctx.java, src/main/java/zmq/IMailbox.java, src/main/java/zmq/Mailbox.java, src/main/java/zmq/MailboxSafe.java, src/main/java/zmq/Msg.java, src/main/java/zmq/SocketBase.java, src/main/java/zmq/ZMQ.java, src/main/java/zmq/io/SessionBase.java, src/main/java/zmq/pipe/Pipe.java, src/main/java/zmq/pipe/YPipe.java, src/main/java/zmq/socket/Sockets.java, src/main/java/zmq/socket/clientserver/Client.java, src/main/java/zmq/socket/clientserver/Server.java, src/test/java/zmq/TestClientServer.java
Solution: port CLIENT and SERVER sockets from libzmq, which are thread-safe sockets.
The thread-safe sockets family includes other sockets, which are not part of this commit.
Also, CLIENT and SERVER cannot be used with a poller at the moment. For poller support, zmq_poller from libzmq has to be ported as well.
=> problem: jeromq is not thread-safe

pom.xml, src/test/java/org/zeromq/guide/AsyncServerTest.java, src/test/java/zmq/socket/pubsub/XpubXsubTest.java
- Adding comment about the purpose of profiles.
- Some tests are flaky, allows build to succeed any way, until this issue
is really resolved.
- Some tests are probably missing timeout, giving a default 5s timeout to them.
=> Improving build

src/main/java/org/zeromq/ZBeacon.java, src/test/java/org/zeromq/ZBeaconTest.java
The builder can be used exclusively, perhaps ZBeacon could be set immutable in a major revision ?
Client and server address was given using a String or a byte[]. Added direct
InetAddress support and deprecate old usage.
The message handler callback was given the full ByteBuffer (65535 bytes). It
now receives only the message payload, including the prefix.
The ZBeacon test was not complete. A few test were added when ZBeacon is
build using a builder.
=> A new ZBeacon implementation.

src/main/java/org/zeromq/ZContext.java, src/test/java/org/zeromq/TestZPoller.java
The Socket.close is enough to handle termination of socket obtained from
a ZContext. The linger value from the context is used as the default value.
=> Should be the last version of close and linger management using ZContext.

src/test/java/org/zeromq/PubSubTest.java, src/test/java/org/zeromq/TestPoller.java, src/test/java/org/zeromq/TestProxy.java, src/test/java/org/zeromq/TestZContext.java, src/test/java/org/zeromq/TestZPoller.java, src/test/java/org/zeromq/ZBeaconTest.java, src/test/java/org/zeromq/guide/EspressoTest.java, src/test/java/zmq/Helper.java, src/test/java/zmq/PollTest.java, src/test/java/zmq/proxy/ProxyTest.java, src/test/java/zmq/socket/pair/TestPairIpc.java
Many tests are flaky, some test failures are ignored, some are too slow. Old Junit assertions are used, trying to reduce code warning.
Not all problems are solved. But it should reduce the number of false negative during CI tests, and perhaps catch some false positive.
A test in ZContext was wrong, it's corrected.
=> Improving some tests

src/main/java/org/zeromq/ZStar.java, src/main/java/zmq/Ctx.java
- an exception caugh in ZStar that should not be.
- Some RuntimeException and IllegalStateException replaced that the usual
exceptions from ØMQ (ZMQException or ZError.IOException
=> Fixing some exceptions

src/main/java/org/zeromq/ZActor.java
An undefined Actor.premiere should not return "?" as it will be the thread name.
Returning null will use an automatic name.
=> An undefine Actor.premiere should not return "?"

src/main/java/zmq/SocketBase.java, src/main/java/zmq/io/SessionBase.java, src/main/java/zmq/io/net/Address.java, src/main/java/zmq/io/net/Listener.java, src/main/java/zmq/io/net/NetProtocol.java, src/main/java/zmq/io/net/tcp/TcpListener.java, src/test/java/zmq/Helper.java, src/test/java/zmq/io/net/tcp/TcpAddressTest.java
- Protocol name was used in place were NetProtocol would be better.
- Using .equals() were == works and is more readable.
- Remove some tests where a simple provider method in enum can do the same with more straigthfull code
- Adding a Listener abstract class, to hide the actual implementation of ipc protocol using tcp.
- NetProtocol.getProcol throws an IllegalArgumentException, more robust than a null that can sneak around. So SocketBase.checkProtocol needs to handle that.
- zmq.io.net.Address was missing a constructor using directly NetProtocol, deprecate the old constructor taking a String.
- Added explicit flag for multicasp transport kind. Is it redudant with subscribe2all ?
- Slightly better NetProtocol.isCompatible, using a Set instead of an List.
=> NetProtocol was not made Enum enough

src/main/java/zmq/io/mechanism/Mechanism.java, src/main/java/zmq/io/mechanism/Mechanisms.java, src/main/java/zmq/io/mechanism/curve/CurveClientMechanism.java, src/main/java/zmq/io/mechanism/curve/CurveServerMechanism.java, src/main/java/zmq/io/mechanism/gssapi/GssapiClientMechanism.java, src/main/java/zmq/io/mechanism/plain/PlainClientMechanism.java, src/test/java/org/zeromq/ZMonitorTest.java
Some events were missed on client side.
In this branch, if CureServerMechanism refuses a connection because the curve
key is invalid, an hard error (with sending the message ERROR) is send, so
connection is no retried. It's done only on first decryption, because only at this
step it's critical. Latter failures means network error, but that's not sure.
=> Finishing improved monitor, with more thorought tests.

src/main/java/org/zeromq/ZContext.java, src/main/java/org/zeromq/ZThread.java, src/test/java/org/zeromq/TestZContext.java
Improved ZContext handling of shadows:
- when it vanishes, all shadows vanish too.
- replaced the static method org.zeromq.ZContext.shadow(ZContext)
with a instance method org.zeromq.ZContext.shadow().
- added a org.zeromq.ZContext.isEmpty() method, that can be used to
ensure good cleaning in tests or asserts.
This is not hierarchical: shadows don't cast shadow.
=> Improved ZContext handling of shadows.

src/main/java/zmq/SocketBase.java
If a socket is monitored twice, the socket for the first monitor is forgotten.
This makes the context termination hang forever.
This commit add a check that throws an IllegalStackException  if it happens.
It's not consistent wit libzmq but it more logical.
=> Leaking sockets with monitor.

src/main/java/zmq/Signaler.java, src/test/java/org/zeromq/TestZContext.java
It's IO are internal, using a Pipe, so it should never hang. Interrupting
a thread waiting for a Signaler loose events that leaks sockets.
So interruptions are masked in some critical sections, and is transformed
in EINTR error.
Exceptions are not lost any more when closing a Signaler.
A test is added to check this.
=> Signaler is now protected from interruption.

src/main/java/zmq/Options.java, src/main/java/zmq/ZMQ.java, src/main/java/zmq/io/mechanism/Mechanism.java, src/main/java/zmq/io/mechanism/NullMechanism.java, src/main/java/zmq/io/mechanism/curve/CurveClientMechanism.java, src/main/java/zmq/io/mechanism/curve/CurveServerMechanism.java, src/main/java/zmq/io/mechanism/plain/PlainClientMechanism.java, src/main/java/zmq/io/mechanism/plain/PlainServerMechanism.java, src/test/java/zmq/TestClientServer.java
This is a problem, because if you want to benefit from thread safe socket in existing system you have to change the entire stack.
For system that already using a single message frame, can benefit from thread-safe socket by using the ZMQ_AS_TYPE option to make the socket use another socket type on the wire
=> problem: New thread-safe sockets cannot communicate with non-thread-safe sockets

src/main/java/zmq/MailboxSafe.java
calling condition.await is -1 returns immediately.
Solution: when timeout is -1 calling the blocking version of await
=> problem: Thread Safe sockets causing high CPU

README.md
The README example code uses a deprecated call to `createSocket(int)`. 
Swapping the `int` parameter for a `SocketType` resolves the deprecation warning.
=> Documentation: Update deprecated createSocket usage in README

src/main/java/org/zeromq/ZMQ.java, src/main/java/zmq/Command.java, src/main/java/zmq/SocketBase.java, src/main/java/zmq/ZError.java, src/main/java/zmq/ZObject.java, src/test/java/org/zeromq/TestZCancellationToken.java
For thread-safe sockets this is an issue because at the moment there is no way to poll over thread-safe sockets.
This PR adds a CancellationToken to allow cancel pending send/recv operation, both for thread-safe and regular sockets
=> problem: cannot cancel ongoing recv/send operation

src/main/java/zmq/Options.java, src/main/java/zmq/io/net/tcp/TcpUtils.java, src/test/java/org/zeromq/TestZMQ.java
It's supported since Java 11, so it's protected by a check.
=> Adding support for ZMQ_TCP_KEEPALIVE_CNT, ZMQ_TCP_KEEPALIVE_IDLE and ZMQ_TCP_KEEPALIVE_INTVL.

src/main/java/zmq/io/net/tcp/TcpUtils.java
It avoid creating an useless object on each call, and more readable.
Exception handling was not consistent. A useless throws IOException is kept
for tuneTcpSocket, even if it's now useless.
=> Simplifications of TcpUtils, using lambda.

src/main/java/zmq/SocketBase.java
This is not the same behavior as with libzmq:
https://github.com/zeromq/libzmq/blob/master/src/socket_base.cpp\#L1215
=> problem: disconnected endpoint laying around forever

src/main/java/org/zeromq/util/ZData.java
This change prevents further reallocations when the `data` content is bigger than 8 bytes
=> minor: initialize `strhex`'s StringBuilder with the correct capacity

src/main/java/org/zeromq/ZContext.java, src/main/java/org/zeromq/ZMQ.java, src/main/java/org/zeromq/ZThread.java, src/main/java/zmq/Ctx.java, src/main/java/zmq/poll/Poller.java, src/test/java/org/zeromq/TestZThread.java, src/test/java/zmq/CtxTest.java, src/test/java/zmq/poll/PollerTest.java
In zmq.poll.Poller.run(), many exceptions were generating stack dump on
stdout.
The thread could also silently die, with an out of memory as an example.
It's now possible to define two UncaughtExceptionHandler in a Ctx that
will be forwarded to the poller.
One (uncaughtExceptionHandler) will be used for the thread's
UncaughtExceptionHandler and should be used to be notify of critical
failures and generate an emergency stop.
The other (notificationExceptionHandler) can be used to replace the old
stack dump, for logging or tests.
it can only be used before any socket was created and not modifed any
more.
=> Exhandlers

.circleci/config.yml, pom.xml
As it's actually non-compliant, it's not in dependency of circle-ci until
failures are all fixed.
It can be used for a quick check with the command:
mvn test -Pandroid -DskipTests
Lint is dropped, as it's don't check any thing and is not reliable.
=> Sniffing the compliance to Android API level 19 in build.

src/main/java/zmq/Options.java, src/test/java/zmq/OptionsTest.java
Socket identity bigger than 127 was failing when the byte array was bigger
that 127, it was stored in a byte that overflow to a negative number.
=> Socket identity bigger than 127 failing

src/main/java/zmq/Command.java, src/main/java/zmq/SocketBase.java, src/main/java/zmq/ZObject.java
**what is the problem**
Hi all. I am using jeromq in a multithreaded environment. but I have a problem same as #721.
I have two threads in my system. One for `sub` recivier, another for `pub` sender. In the recv thread, I directly called `socket.recv()` to recv messages, which will block the thread until a message is received.
When I tried to call `context.close()`, I expect this function call will interrupt recv function, so that I can stop the recv thread directly. In most cases, it worked well. However, there are still hangs.
**how it happened**
I will use the following code to illustrate the problem.
```java
import org.zeromq.SocketType;
import org.zeromq.ZContext;
import org.zeromq.ZMQ;
import org.zeromq.ZMQException;
import zmq.ZError;
public class TestA {
public static void …
```
=> fix: issue 721 deadlock bug

src/main/java/org/zeromq/ZMQ.java, src/main/java/zmq/Options.java, src/main/java/zmq/ZMQ.java, src/main/java/zmq/io/StreamEngine.java, src/main/java/zmq/util/Utils.java, src/test/java/org/zeromq/TestZMQ.java, src/test/java/zmq/OptionsTest.java, src/test/java/zmq/io/MetadataTest.java
Adding a socket option to define a metadata record name where the effective self address used will be stored.
If null (the default) or empty, it will not be stored.
It can be useful in two cases
— when listening with "IP:*", the port is not known
— when listening with "*:XX", the effective address used by the socket is not known.
Allowing to store the effective used address might be useful for auditing.
=> Adding a socket option to define a metadata record name to store the self address

pom.xml
Raising supported Android API to level 28, which the lowest level of supported API on Google Play at the time of this commit.
=> Raising supported Android API to level 28

src/main/java/zmq/io/net/Address.java, src/main/java/zmq/io/net/tcp/TcpUtils.java, src/main/java/zmq/util/Utils.java
Duplication of SocketChannel address resolution in zmq.io.net.tcp.TcpUtils and zmq.Utils.
Deprecating zmq.io.net.tcp.TcpUtils that was not used.
getPeerIpAddress and getLocalIpAddress could throw NPE throught unchecked zmq.io.net.Address::new.
=> Duplication of SocketChannel address resolution in zmq.io.net.tcp.TcpUtils and zmq.Utils.

src/main/java/zmq/io/net/tcp/TcpUtils.java, src/test/java/zmq/io/net/tcp/KeepAliveTest.java
TCP KEEPALIVE values (interval, count and idle) are now really handled. But only works for JVM 13 and latter.
=> TCP KEEPALIVE values (interval, count and idle) are now really handled.

src/main/java/org/zeromq/ZMQ.java
With org.zeromq.ZMQ.Event.recv(socket, DONTWAIT), if they is no more event to receive,
it throws an NPE although the javadoc says it should return null. Fixed.
Also don’t resolve event value for ZMQ_EVENT_MONITOR_STOPPED, it’s a constant.
=> NPE with org.zeromq.ZMQ.Event.recv(socket, DONTWAIT)

src/main/java/org/zeromq/ZCert.java, src/main/java/org/zeromq/ZMQ.java, src/main/java/org/zeromq/ZSocket.java, src/main/java/org/zeromq/util/ZMetadata.java, src/main/java/zmq/io/Metadata.java, src/main/java/zmq/io/StreamEngine.java, src/main/java/zmq/io/mechanism/Mechanism.java, src/test/java/zmq/io/MetadataTest.java
org.zeromq.ZSocket and org.zeromq.ZMQ.Socket can now read and write zmq.Msg directly.
Updating Metada class to provide more data access and functions. ZMetadata is updated too.
It internally now uses ConcurrentHashMap instead of the old Properties class. The Properties class ignore null values, ConcurrentHashMap reject them but ZMTP protocol allows empty values. So null values are transformed to empty strings.
Metada#set is deprecated and replaced by Metada#put, to be more consistent with Map API.
Lots of hostile final method declaration removed.
=> Many updates to metadata handling

src/main/java/zmq/io/SessionBase.java, src/main/java/zmq/io/mechanism/curve/CurveServerMechanism.java, src/test/java/zmq/io/mechanism/MechanismTester.java, src/test/java/zmq/io/mechanism/SecurityCurveTest.java, src/test/java/zmq/io/mechanism/SecurityNullTest.java, src/test/java/zmq/io/mechanism/SecurityPlainTest.java, src/test/java/zmq/io/mechanism/ZapHandler.java
When doing PLAIN or CURVE authentication, the logic can be exchanged.
The client is doing the bind, and the server doing the connect. That was not handled, a connect socket was not expected to reuse the session, and so found an already configured zapPipe. It’s now handled.
Some error message was not returning any message, the specification says that an empty error should be returned instead.
Big rewrite of the tests for mechanisms, the big test function is splited and more code is shared.
=> Inversion of connect/bind with authentications fails.

src/test/java/guide/kvmsg.java, src/test/java/guide/kvmsgTest.java
Without the change the test fails.
=> fix to issue 940 by seting key=null on setKey, added test

src/main/java/org/zeromq/ZContext.java, src/main/java/org/zeromq/ZMQ.java, src/main/java/zmq/Ctx.java, src/main/java/zmq/poll/Poller.java, src/main/java/zmq/poll/PollerBase.java, src/test/java/zmq/poll/PollerBaseTested.java, src/test/java/zmq/poll/PollerTest.java
Ctx can now be provided a thread factory, that can used to tweaks thr…eads.
The main purpose of this is to be able to bind thread to CPU using external libraries like https://github.com/OpenHFT/Java-Thread-Affinity.
The idea was suggested by issue #910
Also adding a check that prevent modifications of some settings once they have been used by Ctx initialisation.
=> Ctx can now be provided a thread factory

.circleci/config.yml, pom.xml, src/main/java/zmq/SocketBase.java
The java compliance is applied using the maven.compiler.release property.
Many plugins update.
The old circleci images was deprecated, using the new one.
=> Upgrading build

src/main/java/zmq/SocketBase.java, src/main/java/zmq/ZMQ.java, src/test/java/zmq/TestMonitor.java
Added a way to specify a custom monitor, that don’t need to communicate throught a ZMQ socket.
It allows to use monitor for logging without hitting hard on the CPU with poller overload.
=> Added a way to specify a custom monitor

doc/monitor.md, src/main/java/org/zeromq/ZEvent.java, src/main/java/org/zeromq/ZMQ.java, src/main/java/org/zeromq/ZMonitor.java, src/main/java/zmq/SocketBase.java, src/main/java/zmq/ZMQ.java, src/main/java/zmq/ZObject.java, src/test/java/org/zeromq/TestEventResolution.java, src/test/java/org/zeromq/TestEvents.java, src/test/java/zmq/TestMonitor.java
Renaming zmq.SocketBase#monitor to zmq.SocketBase#setEventHook, to avoid
ambiguity with socket.monitor(null, events).
Adding a new org.zeromq.ZEvent, that provides a cleaner non compatible
implementation.
Adding org.zeromq.ZMQ.Socket#setEventHook, to provides an high level API
to handle events.
=> Improving monitor

src/main/java/zmq/socket/Peer.java
Because peer socket behave both like client (and server), it should be allowed, like client, to receive a hiccup message.
When a peer socket is the initiator of the connection (calling socket.connect), it should know when there is a disconnect in the connection, just like client.
=> Peer socket should be allow to receive hiccup message

src/main/java/zmq/Ctx.java
I've seen issues where calling `Ctx.terminate()` can hang. It likely traces back to this flag not being marked `volatile`, so that when the reaper thread reaps the last socket, it fails to read the updated value for `terminating`, making it so that [this line](https://github.com/smacke/jeromq/blob/573f3d2f9424b2b4a02f27547610c4c9c013c01e/src/main/java/zmq/Ctx.java#L311) blocks forever.
=> mark Ctx `terminating` flag volatile

pom.xml
Replaces `maven-bundle-plugin` with the more up-to-date `bnd-maven-plugin` and configures it to generate a JPMS module descriptor besides the OSGi descriptor. The descriptor can be generated even using JDK 8 (cf. [documentation](https://bnd.bndtools.org/chapters/330-jpms.html)).
Decompiling the generated descriptor we obtain:
```
org.zeromq.jeromq@0.6.0.SNAPSHOT jar:file:///home/piotr/workspace/jeromq/target/jeromq-0.6.0-SNAPSHOT.jar!/module-info.class
exports org.zeromq
exports org.zeromq.proto
exports org.zeromq.timer
exports org.zeromq.util
exports zmq
exports zmq.io
exports zmq.io.coder
exports zmq.io.coder.raw
exports zmq.io.coder.v1
exports zmq.io.coder.v2
exports zmq.io.mechanism
exports zmq.io.mechanism.curve
exports zmq.io.mechanism.gssapi
exports zmq.io.mechanism.plain
exports …
```
=> Add JPMS module descriptor

src/main/java/zmq/SocketBase.java, src/main/java/zmq/io/SessionBase.java, src/main/java/zmq/io/net/Address.java, src/main/java/zmq/io/net/NetProtocol.java, src/main/java/zmq/io/net/NetworkProtocolProvider.java, src/main/java/zmq/io/net/inproc/InprocNetworkProtocolProvider.java, src/main/java/zmq/io/net/ipc/IpcNetworkProtocolProvider.java, src/main/java/zmq/io/net/norm/NormNetworkProtocolProvider.java, src/main/java/zmq/io/net/pgm/EpgmNetworkProtocolProvider.java, src/main/java/zmq/io/net/pgm/PgmNetworkProtocolProvider.java, src/main/java/zmq/io/net/tcp/TcpAddress.java, src/main/java/zmq/io/net/tcp/TcpConnecter.java, src/main/java/zmq/io/net/tcp/TcpNetworkProtocolProvider.java, src/main/java/zmq/io/net/tipc/TipcNetworkProtocolProvider.java, src/main/resources/META-INF/services/zmq.io.net.NetworkProtocolProvider, src/test/java/zmq/io/AbstractProtocolVersion.java
Protocols are now implemented using ServiceLoader API. It allows easier decoupling of protocol and implementations, or adding new protocols.
=> Network protocols as ServiceProvider.

src/main/java/zmq/SocketBase.java, src/test/java/zmq/TestUnsupported.java
The service implementation for protocol for protocol slightly changed how unsupported one was handled. This pull request fix that.
=> Wrong handling of unsupported protocol, added a test for it.

jeromq-core/src/main/java/org/zeromq/ZMQ.java
Adding a javadoc comment to explain what to use instead.
But adding constant for RADIO and DISH anyway that were missing. This helps the distracted.
=> All the constant for socket types were deprecated in org.zeromq.ZMQ.

jeromq-core/src/main/java/zmq/io/coder/v2/V2Decoder.java, jeromq-core/src/test/java/org/zeromq/ByteBuffersTest.java
Addresses the issue described in https://github.com/zeromq/jeromq/issues/1005
The check added in V2Decoder is the same as the one in V1Decoder to ensure protocol error if the size is less than 0
=> Add check for size in V2Decoder
